console.log('hi');

const url = 'https://randomuser.me/api/?results=12';
let names = [];
fetch(url)
  .then(info => info.json())
  .then(data => {
    let n = data.results[0].name;
    names.push(n);
    console.log(names);
});

function findMatches(wordToMatch, names){
  return names.filter(name => {
    //names must match what is searched
    const regex = new RegExp(wordToMatch, 'gi')//global and match lower/upper case
    return name.first.match(regex) || name.last.match(regex);
  });
}

function displayMatches(){
  console.log(this.value);
}
const searchInput = document.querySelector('.search-input');
console.log(searchInput);
// searchInput.addEventListener('change', ()=>{
//   console.log(e.target.value);
// });


/* FETCH FUNCTIONS */
$.ajax({
  url: 'https://randomuser.me/api/?results=12',
  dataType: 'json',
  success: function(data) {
    let results = data.results;
    //console.log(results);
    displayEmployees(results);

    /*search bar needs added functionality to go through list
    generated by the api and return any matching results*/

    const searchBar = $('<form action="#" method="get"> </form>');
    $(searchBar).append('<input type="search" id="search-input" class="search-input" placeholder="Search...">',
    '<input type="submit" value="&#x1F50D;" id="search-submit" class="search-submit">');
    $('.search-container').append(searchBar);

  }//end success
});

/*///////////////////
    HELP FUNCTIONS
///////////////////*/

//make, Image, First and Last Name, Email, & City  appear
function displayEmployees(data){
  let employeeBubble = '';
  for (let i = 0; i < data.length; i++){
    employeeBubble += `
    <div class="card">
        <div class="card-img-container">
            <img class="card-img" src="${data[i].picture.large}" alt="profile picture">
        </div>
        <div class="card-info-container">
            <h3 id="name" class="card-name cap">${data[i].name.first} ${data[i].name.last}</h3>
            <p class="card-text">${data[i].email}</p>
            <p class="card-text cap">${data[i].location.city}</p>
        </div>
    </div>
    `;

  } //end for
  let g= document.querySelector('#gallery');
  $(g).append(employeeBubble);//show to screen
  //console.log(g);
} //end displayEmployees

/*////////////////////
    EVENT LISTENERS
////////////////////*/


/*//////////////
    POST DATA
//////////////*/
