console.log('hi');

const url = 'https://randomuser.me/api/?results=12';

/*///////////////////
    SEARCH FEATURE
///////////////////*/
/*search bar needs added functionality to go through list
generated by the api and return any matching results*/

const searchBar = $('<form action="#" method="get"> </form>');
$(searchBar).append('<input type="search" id="search-input" class="search-input" placeholder="Search...">',
'<input type="submit" value="&#x1F50D;" id="search-submit" class="search-submit">');
$('.search-container').append(searchBar);

/*///////////////////
    FETCH FUNCTIONS
///////////////////*/

$.ajax({
  url: url,
  dataType: 'json',
  success: function(data) {
    console.log(data.results);
    displayEmployees(data.results);
  }//end success
});

/*///////////////////
    HELP FUNCTIONS
///////////////////*/

//make, Image, First and Last Name, Email, & City  appear
function displayEmployees(data){
  console.log(data);
  let employeeBubble = ''
  for (let i = 0; i < data.length; i++){
    //console.log(data[i]);
    employeeBubble += `
    <div class="card">
        <div class="card-img-container">
            <img class="card-img" src="${data[i].picture.large}" alt="profile picture">
        </div>
        <div class="card-info-container">
            <h3 id="name" class="card-name cap">${data[i].name.first} ${data[i].name.last}</h3>
            <p class="card-text">${data[i].email}</p>
            <p class="card-text cap">${data[i].location.city}</p>
        </div>
    </div>
    `;
  } //end LOOP
  $(employeeBubble).appendTo('#gallery');//show to screen    //console.log(g);


  function popup(){
    //console.log(data);
    let card;
    for(let i = 0; i < data.length; i++){
      let date = data[i].dob.date
      let month = date.slice(5,7);
      let day = date.slice(8,10);
      let year = date.slice(0,4);
      card = `
        <div class="modal-container">
          <div class="modal">
            <button type="button" id="modal-close-btn" class="modal-close-btn"><strong>X</strong></button>
              <div class="modal-info-container">
                <img class="modal-img" src="${data[i].picture.large} " alt="profile picture">
                <h3 id="name" class="modal-name cap">${data[i].name.first} ${data[i].name.last}</h3>
                <p class="modal-text">${data[i].email}</p>
                <p class="modal-text cap">${data[i].location.city}, ${data[i].location.state}</p>
                <hr>
                <p class="modal-text">${data[i].phone}</p>
                <p class="modal-text">${data[i].location.street}, ${data[i].location.state} ${data[i].location.postcode}</p>
                <p class="modal-text">Birthday:${month}/${day}/${year}</p>
              </div>
      `;
      }
      document.querySelector('div').innerHTML += card;

      $('#modal-close-btn').on('click', () => { //make X button work
        $('.modal-container').remove();
      });
  }//end popup

  //when clicked, card should popup
  $('.card').on('click', (e) => {
    console.log(e.target);
    let clickedCard = $('.card').index(e.target); //.eq(i)
    console.log(clickedCard); //not getting expected output
    popup(data[clickedCard]);
    //getting the index of whatever is clicked and showing its data
  });

} //end displayEmployees


function displayMatches(){
  $('.card').hide();
  $('.no-results').hide();
  /*selecting any of the cards text, The first index of the element in the array;
  -1 if not found.*/
  for (let i = 0; i < $('.card').length; i++) {
    const search = $('.card #name').eq(i).text().indexOf($(this).val());
    if (search != -1) {//if found, show card w the match
      $('.card').eq(i).attr("id", "match").show();
    }
  }
  if ($('#match').length < 1) {
    $('.no-results').show();
  }
}

/*////////////////////
    EVENT LISTENERS
////////////////////*/

$('#search-input').on('keyup', displayMatches);//keyup for live search filter
