console.log('hi');

const url = 'https://randomuser.me/api/?results=12';

/*///////////////////
    SEARCH FEATURE
///////////////////*/
/*search bar needs added functionality to go through list
generated by the api and return any matching results*/

const searchBar = $('<form action="#" method="get"> </form>');
$(searchBar).append('<input type="search" id="search-input" class="search-input" placeholder="Search...">',
'<input type="submit" value="&#x1F50D;" id="search-submit" class="search-submit">');
$('.search-container').append(searchBar);

/*///////////////////
    FETCH FUNCTIONS
///////////////////*/

$.ajax({
  url: url,
  dataType: 'json',
  success: function(data) {
    let results = data.results;
    //console.log(results);
    displayEmployees(results);
  }//end success
});

/*///////////////////
    HELP FUNCTIONS
///////////////////*/

//make, Image, First and Last Name, Email, & City  appear
function displayEmployees(data){
  console.log(data);
  let employeeBubble = '';
  for (let i = 0; i < data.length; i++){
    employeeBubble += `
    <div class="card">
        <div class="card-img-container">
            <img class="card-img" src="${data[i].picture.large}" alt="profile picture">
        </div>
        <div class="card-info-container">
            <h3 id="name" class="card-name cap">${data[i].name.first} ${data[i].name.last}</h3>
            <p class="card-text">${data[i].email}</p>
            <p class="card-text cap">${data[i].location.city}</p>
        </div>
    </div>
    `;
  } //end LOOP
  //let g= document.querySelector('#gallery');
  $('#gallery').append(employeeBubble);//show to screen    //console.log(g);

  $('.card').on('click', () => {//when clicked, card should popup
    popup(data[$('.card').index(this)]);
  });
} //end displayEmployees

function popup(data){
  console.log(data);
  let card = '';
  card += `
    <div class="modal-container">
        <div class="modal">
            <button type="button" id="modal-close-btn" class="modal-close-btn"><strong>X</strong></button>
            <div class="modal-info-container">
                <img class="modal-img" src="${data.picture.large} " alt="profile picture">
                <h3 id="name" class="modal-name cap">${data.name.first} ${data.name.last}</h3>
                <p class="modal-text">${data.email}</p>
                <p class="modal-text cap">${data.location.city}</p>
                <hr>
                <p class="modal-text">${data.phone}</p>
                <p class="modal-text">${data.location.street}, ${data.location.state} ${data.location.postcode}</p>
                <p class="modal-text">Birthday:${month}/${day}/${year}</p>
            </div>
            `;

    $('div .modal').append(card);
}

function displayMatches(e){
  $('.card').hide();
  $('.no-results').hide();
  /*selecting any of the cards text, The first index of the element in the array;
  -1 if not found.*/
  for (let i = 0; i < $('.card').length; i++) {
    const search = $('.card #name').eq(i).text().indexOf($(this).val());
    if (search != -1) {//if found, show card w the match
      $('.card').eq(i).attr("id", "match").show();
    }
  }
  if ($('#match').length < 1) {
    $('.no-results').show();
  }
}

/*////////////////////
    EVENT LISTENERS
////////////////////*/

$('#search-input').on('keyup', displayMatches);//keyup for live search
$('#modal-close-btn').on('click', ()=> { //make X button work
  $('.modal-container').remove();
});
/*//////////////
    POST DATA
//////////////*/
